spring:
  application:
    name: product-service
  h2:
    console:
      enabled: true
  datasource:
    name: ecommerce
    url: jdbc:h2:mem:ecommerce
  jpa:
    showSql: true
    hibernate:
      ddlAuto: create-drop

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8081

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://0.0.0.0:8761/eureka/
  instance:
    prefer-ip-address: true